project:
  type: website
  output-dir: docs

website:
  title: "Georgie Samaha"
  #site-url: 
  #google-analytics: ""
  open-graph: true
  navbar:
    background: primary
    search: true
    right:
      - href: about.html
        text: "About"
      - href: science.html
        text: "Science"
      - href: cv.html
        text: "CV"
      - icon: github
        href: https://github.com/georgiesamaha
      - icon: linkedin
        href: https://www.linkedin.com/in/georgie-samaha-95095b230/

format:
  html:
    theme: custom.scss