project:
  type: website
  #resources: 
  #  - resume.pdf
  output-dir: docs

website:
  title: "Georgie Samaha"
  #site-url: 
  #google-analytics: ""
  open-graph: true
  navbar:
    background: primary
    search: true
    right:
      - href: about.html
        text: "About"
      - href: projects.html
        text: "Projects"
      - href: cv.html
        text: "CV"
      - icon: github
        href: https://github.com/georgiesamaha
      - icon: linkedin
        href: https://www.linkedin.com/in/georgie-samaha-95095b230/

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    page-layout: full